# Generated by Django 4.0.1 on 2022-03-02 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0016_remove_cliente_username'),
        ('users', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomecliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='clientes.cliente')),
            ],
        ),
    ]
