# Generated by Django 4.0.1 on 2022-03-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='nomecliente',
        ),
    ]
