# Generated by Django 4.0.1 on 2022-03-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filial',
            name='cliente',
        ),
    ]
