# Generated by Django 4.0.1 on 2022-03-07 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_local_alter_motorista_filial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Local',
        ),
    ]
