# Generated by Django 4.0.1 on 2022-03-07 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_delete_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
        ),
    ]
