# Generated by Django 4.0.1 on 2022-03-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_filial_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupoveiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grupo', models.CharField(max_length=100)),
                ('descricao_grupo', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
