# Generated by Django 4.0.1 on 2022-03-07 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_grupoveiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupoveiculo',
            options={'ordering': ('nome_grupo',), 'verbose_name_plural': 'Grupo de veículos'},
        ),
        migrations.AddField(
            model_name='grupoveiculo',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
        ),
    ]
