# Generated by Django 4.0.1 on 2022-03-07 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0006_veiculo_localinstalacao'),
        ('cadastros', '0008_alter_grupoveiculo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoveiculo',
            name='Veiculo',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to='veiculos.veiculo'),
            preserve_default=False,
        ),
    ]
