# Generated by Django 4.0.1 on 2022-03-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_rename_veiculo_grupoveiculo_veiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupoveiculo',
            name='data_cadastro',
        ),
    ]
