# Generated by Django 4.0.1 on 2022-03-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_remove_grupoveiculo_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoveiculo',
            name='descricao_grupo',
            field=models.CharField(max_length=100, verbose_name='Descrição Grupo'),
        ),
        migrations.AlterField(
            model_name='grupoveiculo',
            name='nome_grupo',
            field=models.CharField(max_length=100, verbose_name='Grupo de veículos'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cpf_motorista',
            field=models.CharField(max_length=100, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='nome_motorista',
            field=models.CharField(max_length=100, verbose_name='Nome do motorista'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='rg_motorista',
            field=models.CharField(max_length=100, verbose_name='RG'),
        ),
    ]
