# Generated by Django 4.0.1 on 2022-03-07 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0011_rename_nomecliente_veiculo_cliente'),
        ('cadastros', '0012_alter_grupoveiculo_descricao_grupo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoveiculo',
            name='veiculo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veiculos.veiculo'),
        ),
    ]
