# Generated by Django 4.0.1 on 2022-03-07 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0011_rename_nomecliente_veiculo_cliente'),
        ('cadastros', '0013_alter_grupoveiculo_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoveiculo',
            name='veiculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='veiculos.veiculo', verbose_name='Veiculos'),
            preserve_default=False,
        ),
    ]
