# Generated by Django 4.0.1 on 2022-03-07 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0025_alter_veiculo_cliente'),
        ('cadastros', '0014_alter_grupoveiculo_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='veiculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='veiculos.veiculo'),
            preserve_default=False,
        ),
    ]
