# Generated by Django 4.0.1 on 2022-03-07 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_filial_veiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filial',
            name='veiculo',
        ),
    ]
