# Generated by Django 4.0.1 on 2022-02-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monitoramento',
        ),
    ]
