# Generated by Django 4.0.1 on 2022-02-10 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('veiculoid', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Veiculo ID')),
                ('statusveiculo', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo'), ('E', 'Espera')], default='', max_length=2, verbose_name='Status')),
                ('placaveiculo', models.CharField(max_length=10, verbose_name='Placa')),
                ('ano_fab', models.CharField(max_length=4, verbose_name='Ano Fabricação')),
                ('ano_mod', models.CharField(max_length=4, verbose_name='Ano Modelo')),
                ('tipoveiculo', models.CharField(choices=[('CM', 'Caminhão'), ('CA', 'Carro'), ('LA', 'Lancha'), ('MO', 'Moto'), ('PU', 'PickUp'), ('TR', 'Trator'), ('VA', 'Van')], max_length=2, verbose_name='Tipo')),
                ('marcaveiculo', models.CharField(choices=[('', 'Audi'), ('', 'Bentley'), ('', 'Chevrolet')], default='', max_length=2, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=15, verbose_name='Modelo')),
                ('cor', models.CharField(max_length=10, verbose_name='Cor')),
                ('chassi', models.CharField(max_length=15, verbose_name='Chassi')),
                ('renavam', models.CharField(max_length=15, verbose_name='Renavam')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
            ],
        ),
    ]
