# Generated by Django 4.0.1 on 2022-02-10 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Veiculos',
            new_name='Veiculo',
        ),
    ]
