# Generated by Django 4.0.1 on 2022-02-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_rename_veiculos_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='ano_fab',
            field=models.IntegerField(verbose_name='Ano Fabricação'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ano_mod',
            field=models.IntegerField(verbose_name='Ano Modelo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='renavam',
            field=models.IntegerField(verbose_name='Renavam'),
        ),
    ]
