# Generated by Django 4.0.1 on 2022-02-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0003_alter_veiculo_ano_fab_alter_veiculo_ano_mod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='marcaveiculo',
            field=models.CharField(choices=[('', 'Acura'), ('', 'Agrale'), ('', 'Alfa Romeo'), ('', 'AM Gem'), ('', 'Asia Motors'), ('', 'Aston Martin'), ('', 'Audi'), ('', 'Baby'), ('', 'BMW'), ('', 'BRM'), ('', 'Bugre'), ('', 'CAB Motors'), ('', 'Cadillac'), ('', 'Caoa Cherry'), ('', 'CBT Jipe'), ('', 'CHANA'), ('', 'Chrysler'), ('', 'Citroen'), ('', 'Cross Lander'), ('', 'Daewoo'), ('', 'Dodge'), ('', 'FIAT'), ('', 'FORD'), ('', 'GM - Chevrolet'), ('', 'Honda'), ('', 'Hyundai'), ('', 'IVECO'), ('', 'JAC'), ('', 'Jaguar'), ('', 'JEEP'), ('', 'KIA Motors')], default='', max_length=2, verbose_name='Marca'),
        ),
    ]
