# Generated by Django 4.0.1 on 2022-02-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0005_alter_veiculo_marcaveiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='localinstalacao',
            field=models.CharField(default='', max_length=50, verbose_name='Local da Instalação'),
        ),
    ]
