# Generated by Django 4.0.1 on 2022-03-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0007_alter_veiculo_marcaveiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='marcaveiculo',
            field=models.CharField(choices=[('', 'Alfa Romeo'), ('', 'Asia Motors'), ('', 'Aston Martin'), ('', 'Audi'), ('', 'BMW'), ('', 'Bugre'), ('', 'Cadillac'), ('', 'Caoa Cherry'), ('', 'Chrysler'), ('', 'Citroen'), ('', 'Cross Lander'), ('', 'Dodge'), ('', 'FIAT'), ('', 'FORD'), ('', 'GM - Chevrolet'), ('', 'Honda'), ('', 'Hyundai'), ('', 'IVECO'), ('', 'JAC'), ('', 'Jaguar'), ('', 'JEEP'), ('', 'KIA Motors'), ('', 'Mercedes-Benz'), ('', 'Mitsubishi'), ('', 'Nissan'), ('', 'Peugeot'), ('', 'Renault'), ('', 'Suzuki'), ('', 'Toyota'), ('', 'Volvo'), ('', 'Volkswagem')], default='', max_length=15, verbose_name='Marca'),
        ),
    ]
