# Generated by Django 4.0.1 on 2022-03-07 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_remove_cliente_username'),
        ('veiculos', '0009_alter_veiculo_marcaveiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='nomecliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marcaveiculo',
            field=models.CharField(choices=[('A', 'Alfa Romeo'), ('A', 'Asia Motors'), ('A', 'Aston Martin'), ('A', 'Audi'), ('B', 'BMW'), ('B', 'Bugre'), ('C', 'Cadillac'), ('C', 'Caoa Cherry'), ('C', 'Chrysler'), ('C', 'Citroen'), ('C', 'Cross Lander'), ('D', 'Dodge'), ('F', 'FIAT'), ('F', 'FORD'), ('G', 'GM - Chevrolet'), ('H', 'Honda'), ('H', 'Hyundai'), ('I', 'IVECO'), ('J', 'JAC'), ('J', 'Jaguar'), ('J', 'JEEP'), ('K', 'KIA Motors'), ('M', 'Mercedes-Benz'), ('M', 'Mitsubishi'), ('N', 'Nissan'), ('P', 'Peugeot'), ('R', 'Renault'), ('S', 'Suzuki'), ('T', 'Toyota'), ('V', 'Volvo'), ('V', 'Volkswagem')], max_length=15),
        ),
    ]
