# Generated by Django 4.0.1 on 2022-03-07 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0010_veiculo_nomecliente_alter_veiculo_marcaveiculo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='nomecliente',
            new_name='cliente',
        ),
    ]
