# Generated by Django 4.0.1 on 2022-03-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0020_veiculo_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='cliente',
        ),
    ]
