# Generated by Django 4.0.1 on 2022-02-09 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_data_cadastro_alter_cliente_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
