# Generated by Django 4.0.1 on 2022-02-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='mensalidade',
            field=models.CharField(
                default='', max_length=5, verbose_name='Mensalidade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='plano',
            field=models.CharField(choices=[('F', 'FIT'), ('S', 'STANDARD'), (
                'P', 'PRIME')], default='', max_length=2, verbose_name='Plano'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vencimento',
            field=models.CharField(
                default='', max_length=2, verbose_name='Vencimento'),
        ),
    ]
