# Generated by Django 4.0.1 on 2022-02-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cliente_mensalidade_cliente_plano_cliente_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='mensalidade',
            field=models.CharField(default='', max_length=5, verbose_name='Mensalidade'),
        ),
    ]
