# Generated by Django 4.0.1 on 2022-02-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_cliente_mensalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='mensalidade',
            field=models.CharField(max_length=10, verbose_name='Mensalidade'),
        ),
    ]
