# Generated by Django 4.0.1 on 2022-02-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_cliente_mensalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='vencimento',
            field=models.CharField(max_length=2, verbose_name='Vencimento'),
        ),
    ]
