# Generated by Django 4.0.1 on 2022-02-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_alter_cliente_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='plano',
            field=models.CharField(choices=[('F', 'FIT'), ('S', 'STANDARD'), ('P', 'PRIME')], max_length=2, verbose_name='Plano'),
        ),
    ]
