# Generated by Django 4.0.1 on 2022-02-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_alter_cliente_plano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='mensalidade',
        ),
    ]
