# Generated by Django 4.0.1 on 2022-02-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_remove_cliente_mensalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='mensalidade',
            field=models.CharField(default='', max_length=10, verbose_name='Mensalidade'),
        ),
    ]
