# Generated by Django 4.0.1 on 2022-03-02 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_cliente_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='username',
        ),
    ]
